theme: jekyll-theme-slate

title: Weird Wings
description: What's weird and wonderful in the world of aviation.

#This section replaces standard URLs in the GitHub Pages theme
repository_url: http://www.weirdwings.com